ip:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  
  joint_controller:
    type: effort_controllers/JointEffortController
    joint: joint1 
